# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-03 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0051_auto_20210222_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOAJDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=False)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='submission.Article')),
            ],
        ),
    ]
