# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identifiers', '0006_crossrefdeposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOAJDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identifiers.Identifier')),
            ],
        ),
    ]
