# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-11 18:51
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import plugins.doaj_transporter.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0051_auto_20210222_1452'),
        ('doaj_transporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('submission.article',),
            managers=[
                ('objects', plugins.doaj_transporter.models.ArticleManager()),
                ('allarticles', django.db.models.manager.Manager()),
            ],
        ),
    ]
